export type Level = 'nhe' | 'vui' | 'chay';
export type Kind = 'truth' | 'dare';

/**
 * Bộ câu theo mức. "{p}" được thay bằng tên một người khác trong bàn lúc rút.
 * Câu không có {p} vẫn chơi được khi chỉ có 2 người.
 */
export const decks: Record<Level, Record<Kind, readonly string[]>> = {
  nhe: {
    truth: [
      'Món ăn nào bạn ghét nhất nhưng vẫn phải ăn vì lịch sự?',
      'Bộ phim gần nhất làm bạn khóc là phim gì?',
      'Biệt danh hồi nhỏ của bạn là gì?',
      'Bạn từng ngủ quên trong hoàn cảnh ngượng nhất nào?',
      'Nếu được đổi tên, bạn muốn tên là gì?',
      'Ấn tượng đầu tiên của bạn về {p} là gì?',
      'Bài hát bạn nghe lặp lại nhiều nhất dạo này?',
      'Nỗi sợ kỳ lạ nhất của bạn là gì?',
      'Bạn từng giả vờ thích món quà nào chưa?',
      'Trong bàn này, ai nấu ăn giỏi nhất theo bạn?',
      'Việc gì bạn hay trì hoãn nhất?',
      'Bạn thích mình ở tuổi nào nhất, vì sao?',
    ],
    dare: [
      'Hát điệp khúc một bài thiếu nhi.',
      'Nói "cảm ơn" bằng 3 thứ tiếng.',
      'Bắt chước tiếng một con vật, cả bàn đoán.',
      'Khen {p} một câu thật lòng.',
      'Kể một câu chuyện cười ngắn.',
      'Làm mặt xấu nhất có thể trong 5 giây.',
      'Đọc thuộc một câu thơ bất kỳ.',
      'Nói giọng phát thanh viên trong lượt tiếp theo.',
      'Cho {p} chọn một biểu tượng cảm xúc, bạn diễn lại nó.',
      'Đứng lên xoay 3 vòng rồi ngồi xuống.',
      'Kể tên 5 loại trái cây trong 5 giây.',
      'Vỗ tay theo nhịp một bài hát, cả bàn đoán bài.',
    ],
  },
  vui: {
    truth: [
      'Lần gần nhất bạn nói dối là chuyện gì?',
      'Chuyện ngượng nhất bạn từng gặp ở chỗ đông người?',
      'Bạn từng viện cớ gì để trốn một buổi hẹn?',
      'Tin nhắn gần nhất bạn gửi mà hối hận là gì?',
      'Thói quen xấu nào bạn chưa từng kể với ai?',
      'Nếu phải đi du lịch với một người trong bàn, bạn chọn ai?',
      'Món quà tệ nhất bạn từng nhận là gì?',
      'Bạn đã từng say đến mức quên đường về chưa?',
      'Điều gì ở {p} làm bạn ghen tị nhất?',
      'Bạn từng thích thầm ai lâu nhất, bao lâu?',
      'Ai trong bàn bạn nghĩ sẽ cưới sớm nhất, vì sao?',
      'Điều gì bạn làm mà bố mẹ vẫn chưa biết?',
    ],
    dare: [
      'Nói giọng miền khác trong 2 lượt tiếp theo.',
      'Cho {p} xem ảnh gần nhất trong máy.',
      'Nhảy một điệu 10 giây, không cần nhạc.',
      'Để {p} đặt biệt danh cho bạn đến hết ván.',
      'Bắt chước dáng đi của {p}.',
      'Nói liền 5 câu không có chữ "không".',
      'Đứng dậy tạo dáng cho cả bàn chụp một tấm.',
      'Giữ mặt nghiêm túc trong khi cả bàn chọc cười 15 giây.',
      'Khen từng người trong bàn một câu.',
      'Uống một ngụm bằng tay không thuận.',
      'Đổi chỗ ngồi với {p} đến hết ván.',
      'Gọi điện cho người thân và nói "con thương mọi người".',
    ],
  },
  chay: {
    truth: [
      'Người yêu cũ nào bạn vẫn còn nghĩ tới?',
      'Bí mật lớn nhất bạn đang giấu bạn bè là gì?',
      'Bạn từng lén xem điện thoại của ai chưa?',
      'Điều bạn hối hận nhất trong năm nay?',
      'Nếu phải hẹn hò với một người trong bàn, bạn chọn ai?',
      'Bạn từng nói xấu {p} sau lưng chưa? Nói gì?',
      'Lần gần nhất bạn khóc vì chuyện tình cảm là khi nào?',
      'Bạn đã từng bị "cắm sừng" hoặc "cắm sừng" ai chưa?',
      'Điều gì khiến bạn mất ngủ nhiều nhất dạo này?',
      'Tin nhắn nào trong máy bạn không muốn ai thấy nhất?',
      'Bạn đánh giá {p} mấy điểm trên 10, vì sao?',
      'Chuyện điên rồ nhất bạn từng làm khi say?',
    ],
    dare: [
      'Đưa máy cho {p} gõ một dòng trạng thái, bạn đăng lên.',
      'Đọc to tin nhắn gần nhất bạn nhận được (được che tên).',
      'Nhắn "mình nhớ cậu" cho người thứ 3 trong danh sách chat.',
      'Để {p} xem lịch sử tìm kiếm 1 phút.',
      'Uống 1 ly mà không dùng tay.',
      'Gọi video cho một người bạn và hát chúc mừng sinh nhật.',
      'Để cả bàn chọn một ảnh đại diện mới cho bạn trong 1 giờ.',
      'Kể một bí mật của bản thân mà chưa ai trong bàn biết.',
      'Nói điều thật lòng nhất bạn muốn nói với {p}.',
      'Uống cạn phần còn lại trong ly.',
      'Cho cả bàn xem ảnh chụp màn hình gần nhất.',
      'Để {p} ra một thử thách bất kỳ, bạn phải làm.',
    ],
  },
};

export const strings = {
  title: 'thật hay thách',
  rule: 'Chọn trả lời thật, làm thử thách, hoặc để máy chọn. Không dám thì uống. Mỗi lượt được đổi câu 1 lần. Chủ phòng chọn mức nhẹ, vui hay cháy ở phòng chờ.',
  levelLabel: 'mức',
  levels: { nhe: 'nhẹ', vui: 'vui', chay: 'cháy' } satisfies Record<Level, string>,
  choose: 'chọn một',
  waitChoose: (name: string) => `${name} đang chọn`,
  kinds: {
    truth: { name: 'thật', hint: 'trả lời thật lòng' },
    dare: { name: 'thách', hint: 'làm thử thách' },
  } satisfies Record<Kind, { name: string; hint: string }>,
  random: 'để máy chọn',
  randomHint: 'không biết chọn gì? máy chọn giúp',
  byMachine: 'máy chọn',
  done: (name: string) => `xong, tới lượt ${name}`,
  swap: 'đổi câu',
  swapUsed: 'đã đổi câu',
  refuse: (penalty: string) => `không dám, ${penalty}`,
  penalty: { nhe: 'nhấp 1 ngụm', vui: 'uống nửa ly', chay: 'uống 1 ly' } satisfies Record<Level, string>,
  tapToFlip: 'chạm để lật',
} as const;
