import type { RoomError } from './net';

export const partyStrings = {
  yourName: 'tên của bạn',
  namePlaceholder: 'ví dụ: Minh',
  needName: 'Nhập tên để mọi người biết ai đang chơi.',
  createRoom: 'tạo phòng',
  codeLabel: 'mã phòng',
  codePlaceholder: '4 số',
  joinRoom: 'vào phòng',
  playLocal: 'chơi trên 1 máy, chuyền tay nhau',
  or: 'hoặc vào phòng của bạn bè',

  players: 'người chơi',
  addPlayer: 'thêm',
  addPlaceholder: 'tên người chơi',
  removePlayer: (name: string) => `bỏ ${name}`,
  needTwo: 'Cần ít nhất 2 người. Lượt chơi đi theo thứ tự danh sách.',
  start: 'bắt đầu chơi',
  back: 'quay lại',

  roomCode: 'mã phòng',
  share: 'mời bạn',
  shareText: (game: string, code: string) => `Vào chơi ${game} cùng mình, mã phòng ${code}`,
  copied: 'đã chép link',
  inviteLink: 'link mời vào phòng',
  inviteHint: 'Gửi link này cho bạn bè, hoặc đọc mã phòng để họ nhập ở màn đầu của game.',
  copyFailed: 'Không chép tự động được. Bấm vào link ở trên, giữ ngón tay để chép.',
  inRoom: (n: number) => `trong phòng (${n})`,
  host: 'chủ phòng',
  you: 'bạn',
  offline: 'mất kết nối',
  waitHost: 'Chờ chủ phòng bắt đầu.',
  hostSets: 'Chủ phòng chỉnh cài đặt.',
  settings: 'cài đặt',
  waitMore: 'Cần ít nhất 2 người trong phòng.',
  leave: 'rời phòng',
  connecting: 'Đang kết nối tới phòng…',

  turn: 'đến lượt',
  yourTurn: 'đến lượt bạn',
  together: 'cả phòng cùng chơi',
  togetherName: (n: number) => `${n} người`,
  waitFor: (name: string) => `Chờ ${name}…`,
  soundOn: 'bật âm thanh',
  soundOff: 'tắt âm thanh',
  endGame: 'kết thúc ván, về phòng chờ',
  endLocal: 'kết thúc ván, sửa người chơi',
  playerOffline: (name: string) => `${name} đang mất kết nối.`,
  skip: 'bỏ lượt',
  hostOffline: 'Chủ phòng đang mất kết nối, chờ họ quay lại.',

  nextTurn: (name: string) => `tới lượt ${name}`,
  safe: 'an toàn',

  errors: {
    'no-room': 'Không có phòng này. Kiểm tra lại mã, hoặc phòng đã đóng.',
    'wrong-game': 'Mã này là phòng của trò khác.',
    full: 'Phòng đã đủ người.',
    busy: 'Server đang quá tải, thử lại sau.',
    bad: 'Dữ liệu không hợp lệ, thử lại.',
  } satisfies Record<RoomError, string>,
} as const;
