const slipWord = (v: number) => (v < 0.25 ? 'bám' : v < 0.6 ? 'hơi trơn' : v < 0.85 ? 'trơn' : 'rất trơn');

export const strings = {
  title: 'snowar.io',
  rule: 'Mỗi người một chú cánh cụt trên tảng băng giữa biển. Lái để lăn cầu tuyết to dần, bắn hoặc húc cho đối thủ trượt xuống nước. Ai trụ lại cuối cùng thắng hiệp; hết giờ thì ai đứng gần tâm băng nhất thắng.',
  rounds: 'Số hiệp',
  map: 'Bản đồ',
  random: 'Ngẫu nhiên',
  scale: 'Cỡ sân',
  scaleEnds: ['Nhỏ', 'Lớn'] as const,
  scaleValue: (v: number) => `${Math.round(v * 100)}%`,
  slip: 'Độ trơn',
  slipEnds: ['Bám', 'Rất trơn'] as const,
  slipWord,
  arena: (map: string, scale: number, slip: number, time: string) => `${map}, sân ${Math.round(scale * 100)}%, mặt băng ${slipWord(slip)}, mỗi hiệp ${time.toLowerCase()}`,
  slipHint: (v: number) => (v < 0.25 ? 'Dừng nhanh, khó bị đẩy rơi.' : v < 0.6 ? 'Trượt vừa phải, dễ làm quen.' : 'Bị húc là trượt rất xa.'),
  preview: 'Xem trước sân',
  randomMaps: 'Bản đồ đổi mỗi hiệp',
  roundsValue: (n: number) => `${n} hiệp`,
  roundTime: 'Thời gian mỗi hiệp',
  roundTimeValue: (s: number) => (s === 0 ? 'Vô hạn' : s < 120 ? `${s} giây` : `${s / 60} phút`),
  noLimit: 'Không giới hạn thời gian',
  garageTitle: 'Chọn áo cho cánh cụt',
  garageHint: 'Màu áo giúp cả phòng nhận ra bạn trên băng.',
  color: 'Màu áo',
  hat: 'Mũ',
  you: 'bạn',
  start: (n: number) => (n > 1 ? `Vào trận với ${n} người` : 'Vào trận'),
  waitStart: (host: string) => `Chờ ${host} cho vào trận`,
  practice: 'Chơi 1 máy: bạn lái chú đầu tiên, các chú còn lại tự lái.',
  round: (n: number, total: number) => `Hiệp ${n}/${total}`,
  clock: (s: number) => `${Math.floor(s / 60)}:${String(s % 60).padStart(2, '0')}`,
  timeLeft: (s: number) => `Còn ${s} giây`,
  go: 'Lăn!',
  fell: (name: string) => `${name} rơi xuống biển`,
  pushed: (by: string, name: string) => `${by} đẩy ${name} xuống biển`,
  spectating: 'Bạn vào giữa hiệp, xem trước rồi chơi từ hiệp sau.',
  out: 'Bạn rơi rồi, xem nốt hiệp nhé.',
  fire: 'Bắn cầu tuyết',
  brake: 'Thắng: giữ để dừng gấp và đứng vững',
  brakeShort: 'Thắng',
  steerHint: 'Kéo để lái. Nút cam: chạm bắn, giữ để đứng vững canh vồng. Giữ Thắng để dừng gấp',
  keysHint: 'Mũi tên hoặc WASD để lái. Space: nhấn bắn thẳng, giữ canh bắn vồng. Shift: giữ để thắng, đứng vững',
  roundWin: (name: string) => `${name} trụ lại cuối cùng`,
  roundDraw: 'Cả bàn cùng rơi, hiệp này hòa',
  timeWin: (name: string) => `Hết giờ, ${name} đứng gần tâm nhất`,
  champion: (name: string, wins: number) => `${name} vô địch với ${wins} hiệp thắng`,
  matchOver: 'Hết trận',
  nextRound: 'Sang hiệp sau',
  backToGarage: 'Về chọn áo, chơi trận mới',
  wins: (n: number) => `${n} thắng`,
  kos: (n: number) => `${n} lần đẩy`,
} as const;
